config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/users/new' => 'users#new'
  post 'users' => 'users#create'

  get '/pages/comrules' => 'pages#comrules'
  get '/pages/term' => 'pages#term'
  get '/sessions/create' => 'sessions#create'
  get '/sessions/destroy' => 'sessions#destroy'
  get 'dashboard' => 'dashboards#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :first_name, :last_name, :password, :presence => true
  validates :email, :uniqueness => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authorize

  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Please login before create."
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authorize, only: [:home, :comrules, :term]
  def home

  end

  def comrules

  end

  def term

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
        sessions[:user_id] = user.id
        redirect_to dashboard_path
    else
        redirect_to login_url, alert: "Invalid username or password."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: "Succesfully Logged Out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update,:destroy]
  skip_before_action :authorize, only: [:new, :create, :index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path , :notice => 'Successful.'
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:email, :password, :first_name, :last_name, :address, :is_admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<h1>Login Successful to DashBoard Index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SGYbco</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/comrules.html.erb
<h1>Community Rules</h1>

app/views/pages/home.html.erb
<div class="header">
  <div class="container">
    <h1>Home Page</h1>
  </div>
</div>

<div class="main">
 <div class="container">
   <%= link_to 'Sign Up', "users/new" %>
   <%= link_to 'Sign In', "sessions/new" %>
 </div>
</div>

app/views/pages/term.html.erb
<h1>Terms of Use, Privacy Policy</h1>

app/views/users/new.html.erb
<div class="header">
  <div class="container">
    <h1>SIGN UP</h1>
  </div>
</div>

<div class="create">
  <div class="container">
    <p><b>Get ready to create, innovate, and change the world.</b></p>
    <br>
    <%= form_for(@user) do |f| %>
        <%= f.hidden_field :username, :value => "Update Username" %>
        <%= f.hidden_field :address, :value => "Update Address" %>
        <%= f.hidden_field :is_admin, :value => false %>

        <% if @user.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <b>Errors</b>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="form-group">
          <%= f.text_field :first_name, class: "form-control", placeholder: "FIRST NAME" %>
        </div>
        <div class="form-group">
          <%= f.text_field :last_name, class: "form-control", placeholder: "LAST NAME" %>
        </div>
        <div class="form-group">
          <%= f.text_field :email, class: "form-control", placeholder: "EMAIL ADDRESS" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: "form-control", placeholder: "PASSWORD" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "PASSWORD CONFIRMATION" %>
        </div>

        <div class="actions">
          <%= f.submit "CREATE ACCOUNT", class: "btn btn-default btn-lg" %>
        </div>
    <% end %>
    <br>
    <p>By signing up, you agree to our <b><%= link_to 'Terms of Use, Privacy Policy', pages_term_path %></b> and
      <b><%= link_to 'Community Rules', pages_comrules_path %>.</b></p>
    <br>
    <p><b>Already have an account? <%= link_to 'Log in', "session/new" %>.</b></p>
  </div>
</div>